# -*- coding: utf-8 -*-
"""插件常量定义"""

from .constants import (
    NAI_PIC_IMAGE_DISPLAY_MARKER,
    MODEL_FORMATS,
    MODEL_MAPPINGS,
    SIZE_MAPPINGS,
    BESTNAI_MODEL_IDS,
    NAI_ACTION_IMAGE_DISPLAY_PREFIX,
    NAI_ACTION_IMAGE_DISPLAY_FALLBACK,
)
from .help_texts import HELP_TEXT, COMMAND_LIST

__all__ = [
    "NAI_PIC_IMAGE_DISPLAY_MARKER",
    "MODEL_FORMATS",
    "MODEL_MAPPINGS",
    "SIZE_MAPPINGS",
    "BESTNAI_MODEL_IDS",
    "NAI_ACTION_IMAGE_DISPLAY_PREFIX",
    "NAI_ACTION_IMAGE_DISPLAY_FALLBACK",
    "HELP_TEXT",
    "COMMAND_LIST",
]
