# -*- coding: utf-8 -*-
"""提示词规则模板"""

from .prompt_rules import (
    PROMPT_GENERATOR_TEMPLATE,
    PROMPT_GENERATOR_JSON_TEMPLATE,
    SFW_PROMPT_GENERATOR_TEMPLATE,
    SFW_PROMPT_GENERATOR_JSON_TEMPLATE,
)

__all__ = [
    "PROMPT_GENERATOR_TEMPLATE",
    "PROMPT_GENERATOR_JSON_TEMPLATE",
    "SFW_PROMPT_GENERATOR_TEMPLATE",
    "SFW_PROMPT_GENERATOR_JSON_TEMPLATE",
]
